apiVersion: v1 # versi api yang digunakan
kind: Service # bertipe Service
metadata: # metadata yang didefinisikan
  name: mongodb-service # nama yang didefinisikan
  namespace: karsa-jobs # namespace yang ditautkan
spec: # spesifikasi yang didefinisikan
  selector: # selector dari service
    app: mongodb # selector pod dengan label -> app === mongodb
  ports: # port yang didefinisikan
  - port: 27017 # port dari service dan port dari pod
