apiVersion: v1 # versi api yang digunakan
kind: Secret # bertipe Secret
metadata: # metadata yang didefinisikan
  name: mongodb-secret # nama yang didefinisikan
  namespace: karsa-jobs # namespace yang ditautkan
type: Opaque # bertipe Opaque
data: # data yang didefinisikan
 MONGO_ROOT_USERNAME: YWRtaW4= # key MONGO_ROOT_USERNAME, value bila decode base64 adalah admin
 MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # key MONGO_ROOT_PASSWORD, value bila decode base64 adalah supersecretpassword
  