apiVersion: v1 # versi api yang digunakan
kind: Service # bertipe Service
metadata: # metadata yang didefinisikan
    name: shipping-service # name yang didefinisikan
    namespace: e-commerce-app # namespace yang ditautkan
spec: # spec yang didefinisikan
    selector: # selector dari service berdasarkan label
        app: shipping # selector pod dengan label = app : shipping
    ports: # menyediakan port yang didefinisikan
        - name: http-request-shipping # nama port ini adalah "http-request-shipping", pastikan nama port selalu unik agar tidak error
          port: 3001 # port yang disediakan service
          targetPort: 3001 # port yang dituju kepada pod