apiVersion: v1 # versi api yang digunakan
kind: Service # bertipe Service
metadata: # metadata yang didefinisikan
  name: karsajobs-service # nama yang didefinisikan
  namespace: karsa-jobs # namespace yang ditautkan
spec: # spesifikasi yang didefinisikan
  type: NodePort # bertipe NodePort
  selector: # selector dari service
    name: karsajobs # selector pod dengan label -> name === karsajobs
  ports: # port yang didefinisikan
  - port: 8080 # port dari service
    targetPort: 8080 # port dari pod
    nodePort: 32000 # port dari nodePort
