apiVersion: v1 # versi api yang digunakan
kind: PersistentVolume # bertipe PersistentVolume
metadata: # metadata yang didefinisikan
  name: rabbitmq-pv # nama yang didefinisikan
  namespace: e-commerce-app # namespace yang ditautkan
spec: # spec yang didefinisikan
  storageClassName: manual # storageClassName yang didefinisikan, harus bernilai sama dengan pvc bila ingin terhubung dengan pvc
  capacity: # kapasitas pv yang didefinisikan
    storage: 1Gi # ukuran storage yang didefinisikan untuk pv
  accessModes: # accessModes pv yang didefinisikan
    - ReadWriteOnce # bertipe ReadWriteOnce, berarti hanya bisa dibaca dalam satu node
  hostPath: # hostPath yang didefinisikan, menggunakan file atau direktori pada node
    path: "/mnt/data" # path dari hostPath

---
 
apiVersion: v1 # versi api yang digunakan
kind: PersistentVolumeClaim # bertipe PersistentVolumeClaim 
metadata: # metadata yang didefinisikan
  name: rabbitmq-pvc # nama yang didefinditautkanisikan
  namespace: e-commerce-app # namespace yang ditautkan
spec: # spec yang didefinisikan
  storageClassName: manual # storageClassName yang didefinisikan, harus bernilai sama dengan pv bila ingin terhubung dengan pv
  accessModes: # accessModes pvc yang didefinisikan
    - ReadWriteOnce # bertipe ReadWriteOnce, berarti hanya bisa dibaca dalam satu node
  resources: # mendefinisikan sumber daya 
    requests: # sumber daya yang diminta
      storage: 1Gi # ukuran storage yang diminta