apiVersion: v1 # versi api yang digunakan
kind: Service # bertipe Service
metadata: # metadata yang didefinisikan
  name: karsajobs-ui-service # nama yang didefinisikan
  namespace: karsa-jobs # namespace yang ditautkan
spec: # spesifikasi yang didefinisikan
  type: NodePort # bertipe NodePort
  selector: # selector dari service
    name: karsajobs-ui # selector pod dengan label -> name === karsajobs-ui
  ports: # port yang didefinisikan
  - port: 8080 # port dari service
    targetPort: 8000 # port dari pod
    nodePort: 32001 # port dari nodePort
 